/**
 * The injected failures, against a real service manager, a real payload and a real daemon.
 *
 * `transaction.test.ts` kills a real updater at every durable boundary and asserts the two steps
 * that follow, but it does it against a **fixture** payload whose entry is a miniature daemon and
 * against a supervisor whose `run` is a seam. That seam is what makes three platforms checkable
 * from one machine, and it is also what it cannot prove:
 *
 * - that the runtime being rolled **back** to is a real `xplainer serve` that takes the real
 *   `owner.lock`, reconciles and binds — so "exactly one process holds `owner.lock`" can be asked
 *   of the lock itself rather than of the process table alone;
 * - that `launchd` (or `systemd`) accepts the rewritten artefact in the rollback direction too;
 * - that a **real** replacement which never becomes ready is stopped, undone and left staged.
 *
 * So this is a proof rather than a test: a script, exit `0` only when every expectation held, and
 * its transcript is the evidence. It is not part of `pnpm verify` — it assembles two ~160 MB
 * payloads and writes to this machine's own service manager — and `scripts/e2e/update.mjs` is what
 * runs it beside the unit suite as `pnpm e2e:update`.
 *
 * ## The four cases
 *
 * 1. **The replacement never becomes ready.** Round 1's second injected failure, made real: B's own
 *    `dist/bin.js` is replaced with a program that starts, binds nothing and writes no
 *    `runtime.json`, and its manifest is regenerated by the shipped scanner so it is a payload the
 *    verifier accepts. The transaction must stop it, switch back, restart A and refuse with the
 *    documented code — and then the **six** assertions hold, the sixth being that the daemon which
 *    came back can render.
 * 2. **`--from B` where B's template pins differ.** Exit `3`, nothing staged, nothing drained, the
 *    daemon still serving, and the message naming the reinstall path **and** the program to run it
 *    from — the one failure that must disturb nothing.
 * 3. **The workspace already matches B and A's pins differ.** The case D9's second clause exists
 *    for: a check written as "does the workspace satisfy the incoming runtime" passes here, and the
 *    rollback target is exactly the runtime it no longer satisfies. It must still refuse.
 * 4. And after each refusal, that the machine is **untouched**: the same staged runtimes, the same
 *    run recorded, no journal, no operation lock — and the daemon **asked**, over an authenticated
 *    `/healthz` that names the release it is serving, rather than inferred from a file it may have
 *    left behind when it died.
 *
 * ## What is real, and the two things that are not
 *
 * Real: both payloads, assembled by the shipped `assembleRuntime()`; the staged copies; the
 * artefact bytes; the supervisor commands; the daemon, which is the real `serve` taking real
 * ownership; the drain, over that daemon's own socket; and `/healthz`, asked with the token the
 * daemon minted.
 *
 * **Not real, and stated rather than glossed:**
 *
 * 1. **The label, on macOS only** — every command is translated to {@link THROWAWAY_LABEL} and the
 *    plist's `Label` rewritten to match, because a proof must not register the product's own label
 *    in a real user's `launchd` (`testing/throwaway-supervisor.ts`). On Linux nothing is
 *    translated, so that leg installs the real `xplainer.service` in the account's own config
 *    directory and removes it in the `finally`: run it on a runner or in
 *    `infra/e2e/Dockerfile.systemd`.
 * 2. **The workspace.** The pre-drain precondition needs a payload 2 that satisfies both runtimes'
 *    pins, and a real one is an `npm ci` of a 268-package tree. This proof writes a fixture
 *    workspace carrying **the real template's pins**, so what is established is that the
 *    precondition reads and verifies a real manifest against the real pins, and that the rolled-back
 *    runtime's own pins are satisfied by what is installed. **The still itself — a PNG out of the
 *    recovered daemon — needs the browser and the real workspace T19 and T33 supply, and B6's
 *    `scripts/e2e/toolchain.mjs` reruns every rollback case to render it.** That split is the plan's
 *    and it is what keeps B5 runnable in its own batch.
 */

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import process from "node:process";
import { readDaemonState, readRuntimeState } from "../../../daemon/daemon-state.js";
import { readLock } from "../../../daemon/lock.js";
import { stateDirLayout } from "../../../daemon/state-dir.js";
import { isAlive } from "../../../daemon/worker-identity.js";
import { assembleRuntime } from "../../../runtime/assemble.js";
import {
  PAYLOAD_LIB_DIR,
  RUNTIME_MANIFEST_FILE,
  type RuntimeManifest,
  scanTree,
} from "../../../runtime/manifest.js";
import { readTemplatePins, verifyWorkspacePayload } from "../../../runtime/verify.js";
import { awaitHealthy } from "../../health.js";
import { installDaemon } from "../../install.js";
import { currentSupervisorEnvironment } from "../../preflight.js";
import { stagedRuntimeRoot } from "../../stage.js";
import { supervisorKindForPlatform } from "../../supervisors/index.js";
import { removeScratchRoot } from "../../testing/scratch.js";
import { writeToolchainMarker } from "../../testing/toolchain.js";
import { updateJournalPath } from "../journal.js";
import { operationLockPath } from "../lock.js";
import { templatePinsOf } from "../stage.js";
import { UpdateRefusal, updateDaemon } from "../transaction.js";
import { fixtureEnvironment } from "./harness.js";
import { renderersAmong, untilProcessesNaming } from "./survivors.js";
import { deregisterThrowaway, throwawayProbe } from "./throwaway-supervisor.js";
import { writeFixtureWorkspace } from "./workspace.js";

/** The label this proof registers under. Never the product's, and booted out in a `finally`. */
export const THROWAWAY_LABEL = "video.xplainer.t16-proof";

/** The version B's copy of `@xplainer/cli` declares, and therefore the release B would report. */
export const PROOF_VERSION = "0.0.0-t16-proof";

/** How long a *deliberate* readiness failure waits before the transaction rolls back. */
const DOOMED_READY_MS = 30_000;

/** The pin B is given in case 2, so its template disagrees with A's by exactly one package. */
const CHANGED_PIN = "remotion";

/**
 * ADR 0020 §6's codes, written out here rather than imported from `daemon/exit-codes.ts`.
 *
 * The correction of 2026-09-08. Reading the production constant on both sides of `===` is a
 * tautology: renumber the constant and every one of these assertions follows it, silently, while
 * the documented contract a caller scripts against has changed. A proof's expectation has to come
 * from the document, so these are the numbers §6 states — `3` for "a precondition of this operation
 * is not met" and `4` for "the daemon is not answering" — and the assertion is that the shipped
 * refusal still carries them.
 */
const DOCUMENTED_EXIT_CODES = { preconditionUnmet: 3, daemonUnhealthy: 4 } as const;

const say = (line: string): void => {
  process.stdout.write(`${line}\n`);
};

/** A failed expectation is the whole point of this script, so each carries its own sentence. */
function require(condition: boolean, what: string): void {
  if (!condition) {
    throw new Error(`FAILED: ${what}`);
  }
  say(`  ok: ${what}`);
}

/** The refusal a call produced, or a failure saying it did not refuse at all. */
async function refusalFrom(act: () => Promise<unknown>): Promise<UpdateRefusal> {
  const error = await act().then(
    () => null,
    (thrown: unknown) => thrown,
  );
  if (!(error instanceof UpdateRefusal)) {
    throw new Error(
      `FAILED: the update was expected to refuse and it ${
        error === null ? "succeeded" : `threw ${String(error)}`
      }`,
    );
  }
  return error;
}

/**
 * Regenerate a payload's manifest after its bytes were changed, with the shipped scanner.
 *
 * This is how B is made a *different* payload without editing the repository mid-proof: the
 * assembler produces two identical trees, and one of them then gets its own
 * `@xplainer/cli/package.json` version and its own entry, rescanned by the same `scanTree()` the
 * assembler used. What lands is byte-for-byte the payload a checkout with those contents would have
 * produced, which is what makes `verifyRuntimePayload()` accept it when the stager re-hashes it.
 */
function rescanPayload(payloadDir: string, cliVersion: string): void {
  const manifestFile = join(payloadDir, RUNTIME_MANIFEST_FILE);
  const manifest = JSON.parse(readFileSync(manifestFile, "utf8")) as RuntimeManifest;
  const rescan = scanTree(payloadDir, { exclude: [RUNTIME_MANIFEST_FILE] });
  const next: RuntimeManifest = {
    ...manifest,
    packages: manifest.packages.map((entry) =>
      entry.name === "@xplainer/cli" ? { ...entry, version: cliVersion } : entry,
    ),
    files: rescan.files,
    links: rescan.links,
  };
  writeFileSync(manifestFile, `${JSON.stringify(next, null, 2)}\n`);
}

/** A file inside a payload's `lib/node_modules/<package>/`. */
function payloadFile(payloadDir: string, packageName: string, ...rest: string[]): string {
  return join(payloadDir, ...PAYLOAD_LIB_DIR.split("/"), ...packageName.split("/"), ...rest);
}

const root = mkdtempSync(join(tmpdir(), "xplainer-t16-proof-"));
const home = join(root, "home");
const stateDir = join(root, "state");
const workspaceRoot = join(stateDir, "workspace");
// macOS renders into a scratch home and registers a throwaway label; Linux has to use this
// account's own config directory, because that is the only place its user manager looks.
const environment =
  process.platform === "darwin" ? fixtureEnvironment(home) : currentSupervisorEnvironment();
const uid = process.getuid?.() ?? 0;
const probe = throwawayProbe(THROWAWAY_LABEL);

try {
  say(`proof root: ${root}`);
  mkdirSync(join(home, "Library", "LaunchAgents"), { recursive: true });
  mkdirSync(join(home, "Library", "Logs"), { recursive: true });
  mkdirSync(stateDir, { recursive: true, mode: 0o700 });

  say("assembling payload A from this checkout");
  const alpha = assembleRuntime({ outDir: join(root, "payload-a") });
  const alphaVersion = (
    JSON.parse(
      readFileSync(payloadFile(alpha.outDir, "@xplainer/cli", "package.json"), "utf8"),
    ) as {
      version: string;
    }
  ).version;
  say(`  A: ${alpha.outDir}, @xplainer/cli ${alphaVersion}`);

  say("assembling payload B, and making it a replacement that never becomes ready");
  const beta = assembleRuntime({ outDir: join(root, "payload-b") });
  const betaPackageFile = payloadFile(beta.outDir, "@xplainer/cli", "package.json");
  const betaPackage = JSON.parse(readFileSync(betaPackageFile, "utf8")) as { version: string };
  betaPackage.version = PROOF_VERSION;
  writeFileSync(betaPackageFile, `${JSON.stringify(betaPackage, null, 2)}\n`);
  // Round 1's second injected failure, and the reason it is this shape rather than an immediate
  // exit: a process that dies is restarted by both supervisors' `on-failure` policies, which would
  // make the case about the supervisor's retries. One that runs and never becomes ready is exactly
  // what the readiness wait exists to catch.
  writeFileSync(
    payloadFile(beta.outDir, "@xplainer/cli", "dist", "bin.js"),
    "// A replacement that starts and never becomes ready: no listener, no runtime.json, no line.\n" +
      "setInterval(() => {}, 60_000);\n",
  );
  rescanPayload(beta.outDir, PROOF_VERSION);
  say(`  B: ${beta.outDir}, @xplainer/cli ${PROOF_VERSION}, an entry that binds nothing`);

  say("writing the setup marker and a workspace carrying the real template's pins");
  writeToolchainMarker(stateDir);
  const pins = readTemplatePins();
  mkdirSync(workspaceRoot, { recursive: true });
  writeFixtureWorkspace({ outDir: workspaceRoot, pins });
  say(
    `  pins: ${String(Object.keys(pins).length)} packages, remotion ${pins.remotion ?? "unpinned"}`,
  );

  say(
    process.platform === "darwin"
      ? `installing A under launchd as ${THROWAWAY_LABEL}`
      : `installing A under ${String(supervisorKindForPlatform(process.platform))}`,
  );
  const install = await installDaemon({
    stateDir,
    payloadDir: alpha.outDir,
    port: 0,
    environment,
    run: probe,
  });
  say(
    `  installed: ${install.runtimeDir}, answering ${install.health.url} as release ` +
      `${install.health.version} after ${String(install.health.elapsedMs)} ms`,
  );
  const installedRun = runIdOf(stateDir);
  say(`  the run answering after the install is ${installedRun ?? "unrecorded"}`);

  // State the newer version wrote, in the shape ADR 0024 gives one: a `format_version` this build
  // does not understand, which that record calls a rollback signal and never corruption.
  const newerRecord = join(stateDir, "jobs", "written-by-the-newer-version.json");
  mkdirSync(join(stateDir, "jobs"), { recursive: true });
  writeFileSync(newerRecord, `${JSON.stringify({ format_version: 99, id: "job-1" })}\n`);
  const newerRecordBytes = readFileSync(newerRecord, "utf8");

  say("");
  say("case 1 — the replacement never becomes ready, so the transaction rolls back");
  const rolledBack = await refusalFrom(() =>
    updateDaemon({
      stateDir,
      from: beta.outDir,
      environment,
      run: probe,
      workspaceRoot,
      healthTimeoutMs: DOOMED_READY_MS,
      log: (line) => {
        say(`  ${line}`);
      },
    }),
  );
  require(rolledBack.exitCode ===
    DOCUMENTED_EXIT_CODES.daemonUnhealthy, `the refusal carries ADR 0020 §6's code ${String(DOCUMENTED_EXIT_CODES.daemonUnhealthy)} for a daemon that is not answering`);
  require(rolledBack.message.includes(
    "is installed and answering",
  ), "the refusal says which runtime is installed and answering now");

  // 1. the previous runtime is running and answering, and it is what the artefact names.
  const back = await awaitHealthy({ stateDir, since: 0, timeoutMs: 30_000, env: process.env });
  require(back.version === alphaVersion, `A is answering ${back.url} as release ${back.version}`);
  require(readDaemonState(stateDir).runtime_dir ===
    install.runtimeDir, "daemon.json records A as the staged runtime the daemon runs out of");
  const artefact = readFileSync(install.artefact, "utf8");
  const stagedBeta =
    readDirectorySorted(stagedRuntimeRoot(stateDir)).find((slot) =>
      slot.startsWith(`${PROOF_VERSION}-`),
    ) ?? "";
  require(stagedBeta !== "", `B was staged as ${stagedBeta}`);
  require(artefact.includes(install.runtimeDir) &&
    !artefact.includes(
      join(stagedRuntimeRoot(stateDir), stagedBeta),
    ), "the artefact the supervisor loaded names A and no longer names B: it was rewritten in the " +
    "rollback direction as well as the forward one");

  // 2. the newer version's state is intact, byte for byte.
  require(readFileSync(newerRecord, "utf8") ===
    newerRecordBytes, "the record a newer format version wrote is preserved exactly");

  // 3. exactly one process holds `owner.lock`, asked of the lock **and** of the process table.
  const held = readLock(stateDirLayout(stateDir).lock);
  const holder = typeof held.record?.pid === "number" ? held.record.pid : null;
  const answering = readRuntimeState(stateDir)?.pid ?? null;
  require(held.state === "parsed", "owner.lock is held and readable");
  require(holder !== null &&
    holder === answering &&
    isAlive(
      holder,
    ), `the process holding owner.lock is the daemon that is answering (pid ${String(holder)})`);
  const surviving = await untilProcessesNaming(root, 1);
  require(surviving.length === 1 &&
    surviving[0]?.includes(install.runtimeDir) ===
      true, `exactly one process runs out of ${root}, and it is A's: ${surviving[0] ?? "<none>"}`);

  // 4. no Chrome and no ffmpeg survives. It has teeth only once a render is in flight, which needs
  //    the browser and the workspace T19 and T33 supply: B6's rerun is where that happens.
  require(renderersAmong(surviving).length ===
    0, "no Chrome and no ffmpeg out of this run survives it");

  // 5. the transaction is closed, and the incoming runtime is left staged rather than removed:
  //    "removing it is a decision this command leaves to you".
  require(!existsSync(
    updateJournalPath(stateDir),
  ), "the journal is gone: the rollback is complete");
  require(!existsSync(operationLockPath(stateDir)), "the operation lock was released");
  require(existsSync(
    join(stagedRuntimeRoot(stateDir), stagedBeta),
  ), "B is still staged, and both runtimes are on disk");

  // 6. and the daemon that came back can render: the workspace on disk satisfies the pins of the
  //    runtime that is installed now, re-hashed by the shipped verifier. The PNG is B6's rerun.
  const readiness = verifyWorkspacePayload(
    workspaceRoot,
    templatePinsOf(install.runtimeDir, "installed"),
  );
  require(readiness.ok, `the installed workspace satisfies the rolled-back runtime's own pins ` +
    `(${String(readiness.checked)} files re-hashed) — the still itself is B6's rerun`);

  say("");
  say("case 2 — B's template pins differ: exit 3, and nothing is disturbed");
  const templateFile = payloadFile(
    beta.outDir,
    "@xplainer/render-core",
    "template",
    "package.json",
  );
  const template = JSON.parse(readFileSync(templateFile, "utf8")) as {
    dependencies?: Record<string, string>;
  };
  const wasPinned = template.dependencies?.[CHANGED_PIN] ?? "unpinned";
  template.dependencies = { ...template.dependencies, [CHANGED_PIN]: "4.0.0-t16-proof" };
  writeFileSync(templateFile, `${JSON.stringify(template, null, 2)}\n`);
  rescanPayload(beta.outDir, PROOF_VERSION);
  say(`  B now pins ${CHANGED_PIN} 4.0.0-t16-proof, where A pins ${wasPinned}`);

  // The run to compare against is the one answering when **this** case starts, and not the one the
  // install left behind: case 1 drained that daemon and the rollback started another.
  const slotsBefore = readDirectorySorted(stagedRuntimeRoot(stateDir));
  const runBeforeRefusal = runIdOf(stateDir);
  const refused = await refusalFrom(() =>
    updateDaemon({ stateDir, from: beta.outDir, environment, run: probe, workspaceRoot }),
  );
  require(refused.exitCode ===
    DOCUMENTED_EXIT_CODES.preconditionUnmet, `the refusal carries ADR 0020 §6's code ${String(DOCUMENTED_EXIT_CODES.preconditionUnmet)} for a precondition that is not met`);
  require(refused.phase === "precondition", "it refused in the precondition, before anything else");
  require(refused.message.includes(
    `${CHANGED_PIN}: installed ${wasPinned}, incoming 4.0.0-t16-proof`,
  ), "the message names the package the two templates disagree about");
  require(refused.message.includes("REINSTALL"), "it says a pin-changing upgrade is a reinstall");
  // Read out of B's own manifest rather than composed: the interpreter is `bin/node.exe` on
  // Windows, and a hard-coded name would make this assertion a POSIX one.
  const betaManifest = JSON.parse(
    readFileSync(join(beta.outDir, RUNTIME_MANIFEST_FILE), "utf8"),
  ) as RuntimeManifest;
  const incomingProgram =
    `${join(beta.outDir, ...betaManifest.launch.interpreter.split("/"))} ` +
    `${join(beta.outDir, ...betaManifest.launch.entry.split("/"))}`;
  require(refused.message.includes(`${incomingProgram} setup --workspace`) &&
    refused.message.includes(
      `${incomingProgram} daemon install --runtime ${beta.outDir}`,
    ), "it names the reinstall path, run from the NEW runtime's own program");
  require(!refused.message.includes(
    join(stateDir, "bin", "xplainer"),
  ), "and never from the installed launcher, which execs the old runtime");
  await requireUntouched(slotsBefore, runBeforeRefusal, alphaVersion);

  say("");
  say("case 3 — the workspace already matches B, and A's pins differ: still exit 3");
  const incomingPins = templatePinsOf(beta.outDir, "incoming");
  writeFixtureWorkspace({ outDir: workspaceRoot, pins: incomingPins });
  require(verifyWorkspacePayload(workspaceRoot, incomingPins)
    .ok, "the workspace satisfies the INCOMING runtime, so a B-against-workspace check would pass");
  require(!verifyWorkspacePayload(workspaceRoot, templatePinsOf(install.runtimeDir, "installed"))
    .ok, "and it no longer satisfies the rollback target, which is what the third clause catches");
  const stillRefused = await refusalFrom(() =>
    updateDaemon({ stateDir, from: beta.outDir, environment, run: probe, workspaceRoot }),
  );
  require(stillRefused.exitCode ===
    DOCUMENTED_EXIT_CODES.preconditionUnmet, "it refuses with §6's exit 3 even though the incoming runtime and the workspace agree");
  await requireUntouched(slotsBefore, runBeforeRefusal, alphaVersion);

  say("");
  say("PROOF PASSED");
} catch (error) {
  process.exitCode = 1;
  process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
} finally {
  say(deregisterThrowaway({ label: THROWAWAY_LABEL, environment, uid }));
  removeScratchRoot(root);
  say(`cleaned up ${root}`);
}

/** The run `runtime.json` records now, which is what "nothing was drained" compares. */
function runIdOf(dir: string): string | null {
  const run = readRuntimeState(dir)?.run_id;
  return typeof run === "string" ? run : null;
}

/** Every entry of a directory, sorted, as the set a refusal must not have added to. */
function readDirectorySorted(path: string): string[] {
  return existsSync(path) ? readdirSync(path).sort() : [];
}

/**
 * The five facts a refusal must leave exactly as it found them, the last one asked of the daemon.
 *
 * The `/healthz` probe is the correction of 2026-09-08. T16 criterion 6 says "the daemon still
 * serving", and until then this function established it by comparing `runtime.json`'s `run_id` —
 * which is a file, not a listener. A daemon that had died without cleaning that file up passed, and
 * so would one killed by the very refusal under test. `awaitHealthy` reads the recorded port and
 * the token the daemon minted and asks it, which is what "still serving" means; the version it
 * answers with says it is still the runtime that was installed before the refusal.
 */
async function requireUntouched(
  slots: readonly string[],
  run: string | null,
  version: string,
): Promise<void> {
  require(readDirectorySorted(stagedRuntimeRoot(stateDir)).join(",") ===
    slots.join(","), `nothing was staged: still ${slots.join(", ")}`);
  require(runIdOf(stateDir) === run, "nothing was drained: the same run is still recorded");
  require(!existsSync(updateJournalPath(stateDir)), "no journal was opened");
  require(!existsSync(operationLockPath(stateDir)), "the operation lock was released");
  const serving = await awaitHealthy({
    stateDir,
    since: 0,
    timeoutMs: 15_000,
    env: process.env,
  }).catch((error: unknown) => {
    throw new Error(
      `FAILED: the daemon is not serving after the refusal: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
  });
  require(serving.version ===
    version, `the daemon is still serving: ${serving.url} answered an authenticated /healthz as ` +
    `release ${serving.version}`);
}
