/**
 * A real update on this machine: two assembled payloads, a real `launchd`, and a real daemon.
 *
 * `transaction.test.ts` proves the ordering, the journal, the precondition and the rollback against
 * a supervisor whose `run` is a seam, and against a fixture payload whose entry is a miniature
 * daemon. That seam is what makes three platforms checkable from one machine, and it is also the
 * one thing it cannot prove: that **`launchd` accepts a rewritten plist**, that the drain travels
 * over the **real** daemon's IPC socket, and that the process which answers afterwards is the real
 * `xplainer serve` out of the new payload.
 *
 * So this is a proof rather than a test: it is a script, it exits `0` only when every expectation
 * held, and it prints the transcript that is the evidence. It is **not** part of `pnpm verify`,
 * because it writes to this machine's own service manager and it assembles two ~160 MB payloads.
 *
 * ```sh
 * pnpm --filter @xplainer/cli build   # the assembler copies dist/, and refuses without it
 * node --import apps/cli/src/daemon/testing/ts-source-hook.ts \
 *   apps/cli/src/install/update/testing/update-proof.ts
 * ```
 *
 * ## What is real, and the two things that are not
 *
 * Real: both payloads, assembled by the shipped `assembleRuntime()` from this checkout, each
 * carrying a copy of this machine's interpreter, npm and the whole `@xplainer/cli` closure; the
 * staged copies; the plist bytes; `launchctl bootout`, `enable`, `bootstrap` and `kickstart`; the
 * daemon, which is the real `xplainer serve` taking real ownership, reconciling and binding both
 * listeners; the drain, which travels over that daemon's own unix socket; and `/healthz`, which is
 * asked with the token the daemon minted.
 *
 * **Not real, and stated rather than glossed:**
 *
 * 1. **The label, on macOS only.** There, every command is translated to {@link THROWAWAY_LABEL}
 *    and the plist's `Label` key is rewritten to match before it is handed to `launchd`, exactly as
 *    `install/testing/supervisor-proof.ts` does and for the same reason: a proof must not register
 *    the product's own label in a real user's `launchd`. Nothing else about the document changes,
 *    and the bytes that are asserted on are the renderer's own. **On Linux nothing is translated**,
 *    because systemd reads `$XDG_CONFIG_HOME/systemd/user` or `~/.config/systemd/user` and nowhere
 *    else — a unit written under a scratch home is a unit the manager never sees — so that leg
 *    installs the product's real `xplainer.service` in this account's own config directory and
 *    removes it in the `finally`. Run the Linux leg on a runner or in the systemd container, which
 *    is what `.github/workflows/daemon-update.yml` and `infra/e2e/Dockerfile.systemd` are for.
 * 2. **The workspace.** The pre-drain precondition needs a payload-2 that satisfies both runtimes'
 *    template pins, and a real one is an `npm ci` of a 268-package tree. This proof writes a
 *    fixture workspace whose manifest carries **the real template's pins**, read from this
 *    checkout's `@xplainer/render-core`. What that establishes is that the precondition reads and
 *    verifies a real manifest against the real pins. That the workspace can **render** is T16's
 *    rollback rerun and `scripts/e2e/toolchain.mjs`, not this script's claim.
 *
 * ## How B gets a different `CLI_VERSION`
 *
 * `version.ts` reads `../package.json` **at startup**, relative to the module — so a payload's
 * reported release is the version in its own copy of `@xplainer/cli/package.json`. B is therefore
 * assembled by the same assembler and then given a different version in that one file, with its
 * manifest regenerated by the shipped `scanTree()`. That is byte-for-byte the payload a checkout
 * with a bumped version would have produced, and it reaches it without editing the repository
 * mid-proof — which a killed run would otherwise leave behind.
 */

import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import process from "node:process";
import { readDaemonState, readRuntimeState } from "../../../daemon/daemon-state.js";
import { assembleRuntime } from "../../../runtime/assemble.js";
import { PAYLOAD_LIB_DIR, RUNTIME_MANIFEST_FILE, scanTree } from "../../../runtime/manifest.js";
import { readTemplatePins } from "../../../runtime/verify.js";
import { installDaemon } from "../../install.js";
import { currentSupervisorEnvironment } from "../../preflight.js";
import { supervisorKindForPlatform } from "../../supervisors/index.js";
import { writeToolchainMarker } from "../../testing/toolchain.js";
import { updateJournalPath } from "../journal.js";
import { updateDaemon } from "../transaction.js";
import { fixtureEnvironment } from "./harness.js";
import { deregisterThrowaway, throwawayProbe } from "./throwaway-supervisor.js";
import { writeFixtureWorkspace } from "./workspace.js";

/** The label this proof registers under. Never the product's, and booted out in a `finally`. */
export const THROWAWAY_LABEL = "video.xplainer.t15-proof";

/** The version B's copy of `@xplainer/cli` declares, and therefore the release B's daemon reports. */
export const PROOF_VERSION = "0.0.0-t15-proof";

const steps: string[] = [];

function say(line: string): void {
  steps.push(line);
  process.stdout.write(`${line}\n`);
}

function require(condition: boolean, what: string): void {
  if (!condition) {
    throw new Error(`FAILED: ${what}`);
  }
  say(`  ok: ${what}`);
}

/**
 * `runProbe`, with every mention of the product's label replaced by the throwaway one.
 *
 * The mechanism, and the reason a proof must not register the product's own label in a real user's
 * `launchd`, are `testing/throwaway-supervisor.ts`'s: two proofs drive a real service manager and a
 * second opinion about how to do it safely is the one thing neither may have.
 */
const labelTranslatingProbe = throwawayProbe(THROWAWAY_LABEL);

const root = mkdtempSync(join(tmpdir(), "xplainer-t15-proof-"));
const home = join(root, "home");
const stateDir = join(root, "state");
const workspaceRoot = join(stateDir, "workspace");
// macOS renders into a scratch home and registers a throwaway label; Linux has to use this
// account's own config directory, because that is the only place its user manager looks.
const environment =
  process.platform === "darwin" ? fixtureEnvironment(home) : currentSupervisorEnvironment();
const uid = process.getuid?.() ?? 0;

try {
  say(`proof root: ${root}`);
  mkdirSync(join(home, "Library", "LaunchAgents"), { recursive: true });
  mkdirSync(join(home, "Library", "Logs"), { recursive: true });
  mkdirSync(stateDir, { recursive: true, mode: 0o700 });

  say("assembling payload A from this checkout");
  const alpha = assembleRuntime({ outDir: join(root, "payload-a") });
  say(`  A: ${alpha.outDir}`);

  say("assembling payload B, then giving its own @xplainer/cli a different version");
  const beta = assembleRuntime({ outDir: join(root, "payload-b") });
  const betaManifestFile = join(beta.outDir, RUNTIME_MANIFEST_FILE);
  const betaPackageFile = join(
    beta.outDir,
    ...PAYLOAD_LIB_DIR.split("/"),
    "@xplainer",
    "cli",
    "package.json",
  );
  const betaPackage = JSON.parse(readFileSync(betaPackageFile, "utf8")) as { version: string };
  const alphaVersion = betaPackage.version;
  betaPackage.version = PROOF_VERSION;
  writeFileSync(betaPackageFile, `${JSON.stringify(betaPackage, null, 2)}\n`);
  const rescan = scanTree(beta.outDir, { exclude: [RUNTIME_MANIFEST_FILE] });
  writeFileSync(
    betaManifestFile,
    `${JSON.stringify(
      {
        ...beta.manifest,
        packages: beta.manifest.packages.map((entry) =>
          entry.name === "@xplainer/cli" ? { ...entry, version: PROOF_VERSION } : entry,
        ),
        files: rescan.files,
        links: rescan.links,
      },
      null,
      2,
    )}\n`,
  );
  say(`  B: ${beta.outDir} — @xplainer/cli ${alphaVersion} → ${PROOF_VERSION}`);

  say("writing the setup marker and a workspace carrying the real template's pins");
  writeToolchainMarker(stateDir);
  const pins = readTemplatePins();
  mkdirSync(workspaceRoot, { recursive: true });
  writeFixtureWorkspace({ outDir: workspaceRoot, pins });
  say(`  pins: ${Object.keys(pins).length} packages, remotion ${pins.remotion ?? "unpinned"}`);

  say(
    process.platform === "darwin"
      ? `installing A under launchd as ${THROWAWAY_LABEL}`
      : `installing A under ${String(supervisorKindForPlatform(process.platform))}`,
  );
  const install = await installDaemon({
    stateDir,
    payloadDir: alpha.outDir,
    port: 0,
    environment,
    run: labelTranslatingProbe,
  });
  say(
    `  installed: ${install.runtimeDir}, answering ${install.health.url} as release ` +
      `${install.health.version} after ${String(install.health.elapsedMs)} ms`,
  );
  const beforeRun = readRuntimeState(stateDir);
  require(install.health.version === alphaVersion, `A answers /healthz as ${alphaVersion}`);
  require(readFileSync(install.artefact, "utf8").includes(
    install.runtimeDir,
  ), "the plist launchd loaded names A's interpreter");

  say("updating to B");
  const outcome = await updateDaemon({
    stateDir,
    from: beta.outDir,
    environment,
    run: labelTranslatingProbe,
    workspaceRoot,
    log: (line) => {
      say(`  ${line}`);
    },
  });

  require(outcome.rolledBack === false, "the transaction completed rather than rolling back");
  require(outcome.commands.some((command) =>
    command.startsWith("POST /api/daemon/drain"),
  ), "the running daemon was drained over its own socket, not stopped through launchd");
  const plist = readFileSync(outcome.supervisor.artefact, "utf8");
  require(plist.includes(outcome.incoming.runtime_dir) &&
    !plist.includes(
      install.runtimeDir,
    ), "the artefact's program moved: the plist names B's interpreter and no longer names A's");
  require(readDaemonState(stateDir).runtime_dir ===
    outcome.incoming
      .runtime_dir, "daemon.json records B as the staged runtime the daemon runs out of");
  require(outcome.health.version ===
    PROOF_VERSION, `/healthz reports B: release ${outcome.health.version}`);
  require(outcome.runId !==
    (beforeRun?.run_id ??
      null), "the run that answered is a new run, not the one that was drained");
  require(existsSync(outcome.previous.runtime_dir), "A is retained on disk for a rollback");
  require(!existsSync(
    updateJournalPath(stateDir),
  ), "the journal is gone, which is how a completed transaction is recorded");

  say("PROOF PASSED");
} catch (error) {
  process.exitCode = 1;
  process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
} finally {
  // Whatever happened, this machine's launchd goes back to holding nothing of ours.
  process.stdout.write(`${deregisterThrowaway({ label: THROWAWAY_LABEL, environment, uid })}\n`);
  rmSync(root, { recursive: true, force: true });
  process.stdout.write(`cleaned up ${root}\n`);
}
