#!/usr/bin/env node
/**
 * Generate both language bindings for the tool contract, in one invocation.
 *
 * `schemas/` is the source of truth. Everything under `src/generated/` and
 * `python/xplainer_protocol/generated/` is derived from it and is diffed in CI
 * (plan AC-9c), so this script has one hard requirement beyond correctness:
 * running it twice over an unchanged `schemas/` must produce byte-identical
 * output. That is why
 *
 *   - both generators are pinned to exact versions (`json-schema-to-typescript`
 *     in package.json, `datamodel-code-generator` in the root pyproject.toml),
 *   - `datamodel-codegen` runs with `--disable-timestamp`, and its own comment
 *     header — which carries the input filename — is stripped and replaced with
 *     ours, so a temporary path can never leak into a committed file,
 *   - every list this script walks is sorted, so filesystem ordering cannot
 *     reorder the output.
 *
 * Both languages are written by one command on purpose: generating them
 * separately is how a commit ends up with a regenerated TypeScript half and a
 * stale Python one.
 *
 * Usage:
 *   node scripts/codegen.mjs           write the generated files
 *   node scripts/codegen.mjs --check   fail if the files on disk are stale
 */

import { spawnSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile } from "json-schema-to-typescript";

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REPO_ROOT = path.resolve(PACKAGE_ROOT, "..", "..");
const SCHEMAS_DIR = path.join(PACKAGE_ROOT, "schemas");
const TOOLS_DIR = path.join(SCHEMAS_DIR, "tools");
const TS_OUT_DIR = path.join(PACKAGE_ROOT, "src", "generated");
const PY_OUT_DIR = path.join(PACKAGE_ROOT, "python", "xplainer_protocol", "generated");

/**
 * Separator `datamodel-code-generator` puts between top-level definitions.
 *
 * Two blank lines, which is PEP 8 and what the generator emits; the open-enum
 * post-processing below splits on it to find one class body exactly. It is named
 * here so a generator upgrade that changed the spacing fails at the assertion in
 * {@link withOpenEnumFallbacks} rather than silently dropping the fallback.
 */
const PY_DEFINITION_SEPARATOR = "\n\n\n";

/** Marker every emitted file opens with, so an edited file is obvious in review. */
const MARKER = "generated by codegen.mjs — do not edit";
const TS_HEADER = [
  `// ${MARKER}`,
  "// Source of truth: packages/protocol/schemas/**",
  "// Regenerate with: pnpm --filter @xplainer/protocol codegen",
  "",
].join("\n");
const PY_HEADER = [
  `# ${MARKER}`,
  "# Source of truth: packages/protocol/schemas/**",
  "# Regenerate with: pnpm --filter @xplainer/protocol codegen",
  "",
].join("\n");

/** Read and parse one JSON file. */
function readJson(file) {
  return JSON.parse(readFileSync(file, "utf8"));
}

/**
 * Every schema file that describes a type, sorted by its path relative to
 * `schemas/`. `manifest.json` is excluded: it is a data document listing the
 * tools, not a schema describing a value.
 */
function schemaFiles() {
  const shared = readdirSync(SCHEMAS_DIR).filter(
    (name) => name.endsWith(".json") && name !== "manifest.json",
  );
  const tools = readdirSync(TOOLS_DIR)
    .filter((name) => name.endsWith(".json"))
    .map((name) => path.posix.join("tools", name));
  return [...shared, ...tools].sort();
}

/** The tool names, in manifest order. That order is the contract order. */
function toolNames() {
  return readJson(path.join(SCHEMAS_DIR, "manifest.json")).tools.map((tool) => tool.name);
}

/**
 * The scaffold files the engine owns, in manifest order — which is max's
 * scaffold order, so the generated tuple can be read alongside a scaffold
 * listing without reordering.
 *
 * Emitted beside `TOOL_NAMES` because it is the same kind of thing: one list in
 * `schemas/manifest.json` that several surfaces must agree on. `render-core`
 * scaffolds and restores these files, `@xplainer/mcp-server` refuses a write to
 * one, and `explainer_put_source.input.json` reserves the same five in a
 * `not`/`enum` — all from here, so none of them can drift.
 */
function engineOwnedFiles() {
  const files = readJson(path.join(SCHEMAS_DIR, "manifest.json")).engine_owned_files;
  if (!Array.isArray(files) || files.length === 0) {
    throw new Error(
      "codegen: schemas/manifest.json has no `engine_owned_files` array. It is the " +
        "authoritative list of the scaffold files an agent may not write.",
    );
  }
  return files;
}

/**
 * The manifest's contract version — the number the shim compares, not a release
 * number.
 *
 * It is read here rather than imported at runtime by the packages that need it,
 * because `packages/protocol` builds with `rootDir: src` and a `schemas/`
 * import from inside `src/` would not compile.
 */
function contractVersion() {
  const version = readJson(path.join(SCHEMAS_DIR, "manifest.json")).version;
  if (typeof version !== "string" || version === "") {
    throw new Error("codegen: schemas/manifest.json has no `version` string.");
  }
  return version;
}

/**
 * The enums a consumer must decode leniently, as `[title, fallbackMember]`
 * pairs sorted by title, each validated against the schema that defines it.
 *
 * Openness is declared in `schemas/manifest.json` rather than in the schema
 * document itself: a vendor keyword such as `x-open-enum` is rejected outright
 * by a strict Ajv instance (`strict mode: unknown keyword`), and `schemas/` is a
 * published surface a consumer may compile strictly. `manifest.json` is a data
 * document nothing compiles as a schema, which is where `engine_owned_files`
 * already lives for the same reason.
 *
 * The policy this implements is ADR 0024 §Note, 2026-09-06: P1-S3 settled —
 * adding a member is a minor contract change precisely *because* both generated
 * decoders accept an unrecognised value and fall back.
 */
function openEnums() {
  const manifest = readJson(path.join(SCHEMAS_DIR, "manifest.json"));
  const declared = manifest.open_enums ?? {};
  if (typeof declared !== "object" || Array.isArray(declared)) {
    throw new Error(
      "codegen: schemas/manifest.json's `open_enums` must be an object mapping a schema " +
        "title to the member an unrecognised value falls back to.",
    );
  }

  const byTitle = new Map();
  for (const relative of schemaFiles()) {
    const schema = readJson(path.join(SCHEMAS_DIR, relative));
    byTitle.set(schema.title, { relative, schema });
  }

  return Object.keys(declared)
    .sort()
    .map((title) => {
      const entry = byTitle.get(title);
      if (entry === undefined) {
        throw new Error(`codegen: open_enums names \`${title}\`, which no schema defines.`);
      }
      const { schema, relative } = entry;
      if (schema.type !== "string" || !Array.isArray(schema.enum)) {
        throw new Error(
          `codegen: open_enums names \`${title}\`, but ${relative} is not a string enum.`,
        );
      }
      const fallback = declared[title];
      if (!schema.enum.includes(fallback)) {
        throw new Error(
          `codegen: open_enums maps \`${title}\` to \`${fallback}\`, which is not one of its ` +
            `members in ${relative}.`,
        );
      }
      return { title, fallback, values: schema.enum, relative };
    });
}

/** `JobErrorCode` → `JOB_ERROR_CODE`. The screaming-snake half of a generated name. */
function screamingSnake(pascalCase) {
  return pascalCase.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

// ── TypeScript ─────────────────────────────────────────────────────────────

/**
 * Split one `json-schema-to-typescript` output into its top-level
 * declarations, each carrying the JSDoc block that precedes it.
 *
 * Needed because the schemas cross-reference each other: compiling
 * `tools/explainer_job.output.json` also emits `JobState`, and so does
 * compiling `job-state.json`. Splitting lets identical declarations be
 * collapsed and genuinely conflicting ones be reported instead of silently
 * emitting a file that does not compile.
 */
function splitDeclarations(source) {
  const blocks = [];
  let current = [];
  let currentHasDeclaration = false;
  let depth = 0;
  let inComment = false;

  for (const line of source.split("\n")) {
    // A new top-level declaration starts at column zero, outside any block
    // comment and outside any braced body. Property JSDoc inside an interface
    // is indented, so it cannot be mistaken for one. A leading JSDoc block is
    // kept with the declaration it documents, which is why the split only
    // happens once the current block already holds a declaration.
    const atTopLevel = !inComment && depth === 0;
    const startsBlock = atTopLevel && /^(\/\*|export |declare )/.test(line);
    if (startsBlock && currentHasDeclaration) {
      blocks.push(current);
      current = [];
      currentHasDeclaration = false;
    }
    if (line.trim() === "" && current.length === 0) {
      continue;
    }
    current.push(line);
    if (atTopLevel && /^(export |declare )/.test(line)) {
      currentHasDeclaration = true;
    }

    if (inComment) {
      if (line.includes("*/")) {
        inComment = false;
      }
      continue;
    }
    const commentStart = line.indexOf("/*");
    if (commentStart !== -1 && !line.includes("*/", commentStart)) {
      inComment = true;
    }
    // Braces inside comment text must not move the depth, so only the code that
    // precedes a comment on this line is counted.
    const code = commentStart === -1 ? line : line.slice(0, commentStart);
    for (const character of code) {
      if (character === "{") {
        depth += 1;
      } else if (character === "}") {
        depth -= 1;
      }
    }
  }
  if (current.some((entry) => entry.trim() !== "")) {
    blocks.push(current);
  }

  return blocks.map((block) => block.join("\n").trim()).filter((block) => block !== "");
}

/** The exported name a declaration block introduces. */
function declarationName(block) {
  const match = block.match(/^export (?:declare )?(?:interface|type|const|enum) ([A-Za-z0-9_$]+)/m);
  if (match === null) {
    throw new Error(
      `codegen: could not find an exported name in this generated block:\n${block}\n` +
        "The declaration splitter and json-schema-to-typescript's output format have diverged.",
    );
  }
  return match[1];
}

/**
 * Compile every schema to TypeScript and merge the results into one module.
 *
 * A name emitted twice with identical text is one shared type reached from two
 * schemas, and is collapsed. A name emitted twice with different text means two
 * schemas gave the same `title` to different shapes; that is a contract bug, so
 * it throws rather than picking a winner.
 */
async function generateTypes() {
  /** @type {Map<string, {text: string, from: string}>} */
  const declarations = new Map();

  for (const relative of schemaFiles()) {
    const absolute = path.join(SCHEMAS_DIR, relative);
    const compiled = await compileFromFile(absolute, {
      bannerComment: "",
      additionalProperties: false,
      declareExternallyReferenced: true,
      cwd: path.dirname(absolute),
      unknownAny: true,
    });

    for (const block of splitDeclarations(compiled)) {
      const name = declarationName(block);
      const existing = declarations.get(name);
      if (existing === undefined) {
        declarations.set(name, { text: block, from: relative });
        continue;
      }
      if (existing.text !== block) {
        throw new Error(
          `codegen: two schemas define \`${name}\` differently — ` +
            `${existing.from} and ${relative}. Schema titles must be unique across ` +
            "packages/protocol/schemas/, because they become TypeScript type names.",
        );
      }
    }
  }

  const names = [...declarations.keys()].sort();
  const body = names.map((name) => declarations.get(name).text).join("\n\n");
  return `${TS_HEADER}\n${body}\n`;
}

/** The frozen tool-name and engine-owned-file tuples, TypeScript side. */
function generateTsManifest(names, engineOwned, version) {
  const entries = names.map((name) => `  ${JSON.stringify(name)},`).join("\n");
  const engineEntries = engineOwned.map((name) => `  ${JSON.stringify(name)},`).join("\n");
  // `isolatedDeclarations` forbids inferring an exported const's type from the
  // initialiser, so the tuple type is written out. It is built from the same
  // `names`/`engineOwned` arrays as the values below, which is what keeps a
  // re-run byte-identical (AC-9c).
  const toolTuple = names.map((name) => JSON.stringify(name)).join(", ");
  const engineTuple = engineOwned.map((name) => JSON.stringify(name)).join(", ");
  return `${TS_HEADER}
/**
 * The eight explainer tools, in contract order.
 *
 * Frozen at runtime and \`as const\` at compile time, so neither a caller nor a
 * later refactor can reorder or extend the list without changing
 * \`schemas/manifest.json\`, which is where the contract actually lives. Every
 * surface that serves the protocol iterates this tuple rather than repeating
 * the names.
 */
export const TOOL_NAMES: readonly [${toolTuple}] = Object.freeze([
${entries}
] as const);

/** One of the eight tool names. */
export type ToolName = (typeof TOOL_NAMES)[number];

/**
 * The scaffold files the engine owns, in scaffold order.
 *
 * These five mount the narration audio, the caption track and the per-segment
 * sequencing. An agent that rewrote one could drop the soundtrack and still
 * render successfully, so \`explainer_put_source\` refuses to write them and the
 * scaffold generator restores them from its templates. The agent owns
 * \`Scenes.tsx\` and everything it imports instead.
 *
 * Frozen and \`as const\` for the same reason as {@link TOOL_NAMES}: the list
 * lives in \`schemas/manifest.json\`, and no consumer gets to extend or narrow it
 * at runtime.
 */
export const ENGINE_OWNED_FILES: readonly [${engineTuple}] = Object.freeze([
${engineEntries}
] as const);

/** One of the engine-owned scaffold file names. */
export type EngineOwnedFile = (typeof ENGINE_OWNED_FILES)[number];

/**
 * The version of the **tool contract**, from \`schemas/manifest.json\`.
 *
 * Not a release version. \`@xplainer/cli\` and the hosted image each have their
 * own \`version\`, and the MCP \`initialize\` handshake reports *that* in
 * \`serverInfo.version\`, which is why the handshake cannot be used to detect
 * contract skew. This number is what \`xplainer serve\` advertises on
 * \`GET /healthz\` as \`contract_version\` and what
 * {@link isContractCompatible} compares
 * ([ADR 0025](../../../../docs/adr/0025-daemon-updates-and-readiness.md)
 * §Note, 2026-09-06: P1-S3 settled).
 *
 * It lives here, in the package that owns the contract, rather than in
 * \`@xplainer/mcp-server\`: the \`xplainer mcp --attach\` shim must read it
 * before any MCP session exists, and \`@xplainer/protocol\` is the one package
 * every surface already depends on.
 */
export const MCP_CONTRACT_VERSION: string = ${JSON.stringify(version)};
`;
}

/**
 * The lenient decoders for the enums `schemas/manifest.json` marks open.
 *
 * A TypeScript union is erased at runtime, so the *type* tolerates an unknown
 * value already and proves nothing; what a consumer needs is a function that
 * turns a string off the wire into a member of the union. That is what is
 * emitted here, and it is the TypeScript half of the tolerance the Python
 * `_missing_` hook provides — one policy, two languages, one generator.
 */
function generateTsOpenEnums(open) {
  if (open.length === 0) {
    throw new Error(
      "codegen: schemas/manifest.json declares no `open_enums`. Adding an `error_code` member " +
        "is a minor contract change only because the generated decoders tolerate one " +
        "(ADR 0024 §Note, 2026-09-06: P1-S3 settled), so an empty table would silently " +
        "reclassify every future member as breaking.",
    );
  }
  const titles = open.map((entry) => entry.title);
  const blocks = open.map(({ title, fallback, values, relative }) => {
    const constant = `${screamingSnake(title)}_VALUES`;
    const tuple = values.map((value) => JSON.stringify(value)).join(", ");
    const entries = values.map((value) => `  ${JSON.stringify(value)},`).join("\n");
    const lookup = values
      .map((value) => `  [${JSON.stringify(value)}, ${JSON.stringify(value)}],`)
      .join("\n");
    return `/**
 * Every ${title} member this build of the contract knows, in schema order.
 *
 * Frozen for the same reason as \`TOOL_NAMES\`: the list lives in
 * \`schemas/${relative}\`, and no consumer gets to extend or narrow it at
 * runtime. A daemon newer than this build may send a member that is not in
 * here; {@link to${title}} is how such a value is decoded.
 */
export const ${constant}: readonly [${tuple}] = Object.freeze([
${entries}
] as const);

/**
 * Members of {@link ${constant}}, by their own wire value.
 *
 * A \`Map\` and not an object literal: an object lookup answers \`"toString"\`
 * with a function inherited from \`Object.prototype\`, which would let the
 * decoder below return something that is not a member at all.
 */
const ${screamingSnake(title)}_BY_VALUE: ReadonlyMap<string, ${title}> = new Map<string, ${title}>([
${lookup}
]);

/**
 * Decode a ${title} off the wire, falling back to \`${fallback}\` for a member
 * this build does not know.
 *
 * The enum is **open**: adding a member is a minor contract change, and a minor
 * bump must not break a shim that is already attached, so an unrecognised value
 * decodes rather than throwing. The detail is not lost — \`error\` carries the
 * human-readable half of the same failure and is never rewritten.
 */
export function to${title}(value: string): ${title} {
  return ${screamingSnake(title)}_BY_VALUE.get(value) ?? ${JSON.stringify(fallback)};
}`;
  });

  return `${TS_HEADER}
/**
 * Lenient decoders for the open enums, generated from \`schemas/manifest.json\`'s
 * \`open_enums\` table.
 *
 * Openness is a property of the contract, not of a consumer: ADR 0024's
 * P1-S3 note classifies adding a member as a **minor** change *because* every
 * generated decoder tolerates an unknown one. Delete a decoder and that
 * classification stops being true.
 */

import type { ${titles.join(", ")} } from "./types.js";

${blocks.join("\n\n")}
`;
}

// ── Python ─────────────────────────────────────────────────────────────────

/**
 * Rewrite one `$ref` into a pointer inside the bundle built below.
 *
 * Cross-file references (`../slug.json`) become `#/$defs/<Title>`; references
 * that are already local (`#/$defs/SourceFile`) survive unchanged, because
 * every nested `$defs` entry is hoisted to the bundle root under the same name.
 */
function rewriteRef(ref, titleByRelativePath, sourceRelativePath) {
  if (ref.startsWith("#")) {
    return ref;
  }
  const [file, pointer = ""] = ref.split("#");
  const resolved = path.posix.normalize(
    path.posix.join(path.posix.dirname(sourceRelativePath), file),
  );
  const title = titleByRelativePath.get(resolved);
  if (title === undefined) {
    throw new Error(
      `codegen: ${sourceRelativePath} references ${ref}, which is not a schema file.`,
    );
  }
  if (pointer === "") {
    return `#/$defs/${title}`;
  }
  const nested = pointer.match(/^\/\$defs\/([A-Za-z0-9_]+)$/);
  if (nested === null) {
    throw new Error(
      `codegen: ${sourceRelativePath} references ${ref}. Only a whole schema or one of its ` +
        "`$defs` entries can be referenced across files, because that is what the bundle hoists.",
    );
  }
  return `#/$defs/${nested[1]}`;
}

/** Recursively rewrite every `$ref` in a schema fragment. */
function rewriteRefs(node, titleByRelativePath, sourceRelativePath) {
  if (Array.isArray(node)) {
    return node.map((item) => rewriteRefs(item, titleByRelativePath, sourceRelativePath));
  }
  if (node === null || typeof node !== "object") {
    return node;
  }
  const out = {};
  for (const key of Object.keys(node)) {
    if (key === "$ref" && typeof node[key] === "string") {
      out[key] = rewriteRef(node[key], titleByRelativePath, sourceRelativePath);
      continue;
    }
    out[key] = rewriteRefs(node[key], titleByRelativePath, sourceRelativePath);
  }
  return out;
}

/**
 * Fold every schema file into one self-contained document under `$defs`.
 *
 * `datamodel-code-generator` emits a Python package rather than a single module
 * when handed a directory, and the plan fixes the output at one `models.py`, so
 * the many files are bundled here instead. Keys are sorted, so the order of
 * classes in the generated module is fixed.
 */
function buildPythonBundle() {
  const files = schemaFiles();
  const titleByRelativePath = new Map();
  for (const relative of files) {
    const schema = readJson(path.join(SCHEMAS_DIR, relative));
    if (typeof schema.title !== "string") {
      throw new Error(
        `codegen: ${relative} has no \`title\`, so it cannot be named in either language.`,
      );
    }
    titleByRelativePath.set(relative, schema.title);
  }

  const defs = {};
  const definedBy = new Map();
  const define = (name, fragment, source) => {
    const previous = definedBy.get(name);
    if (previous !== undefined) {
      if (JSON.stringify(defs[name]) !== JSON.stringify(fragment)) {
        throw new Error(
          `codegen: two schemas define \`${name}\` differently — ${previous} and ${source}.`,
        );
      }
      return;
    }
    defs[name] = fragment;
    definedBy.set(name, source);
  };

  for (const relative of files) {
    const schema = rewriteRefs(
      readJson(path.join(SCHEMAS_DIR, relative)),
      titleByRelativePath,
      relative,
    );
    const nested = schema.$defs ?? {};
    const root = {};
    for (const key of Object.keys(schema)) {
      // `$schema` is meta-information about the file, and `$defs` is hoisted to
      // the bundle root below; neither belongs inside a bundled definition.
      if (key !== "$schema" && key !== "$defs") {
        root[key] = schema[key];
      }
    }
    for (const nestedName of Object.keys(nested).sort()) {
      define(nestedName, nested[nestedName], relative);
    }
    define(root.title, root, relative);
  }

  const sorted = {};
  for (const name of Object.keys(defs).sort()) {
    sorted[name] = defs[name];
  }
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "XplainerProtocol",
    description:
      "Codegen anchor with no fields of its own. datamodel-code-generator always " +
      "emits a model for the root of its input, and the root here is the bundle " +
      "of every schema in packages/protocol/schemas rather than a value anyone " +
      "sends. The types that matter are the ones below it.",
    type: "object",
    additionalProperties: false,
    properties: {},
    $defs: sorted,
  };
}

/** Strip the generator's own comment header so no input path can reach the file. */
function replaceHeader(source, header) {
  const lines = source.split("\n");
  let index = 0;
  while (index < lines.length && (lines[index].startsWith("#") || lines[index].trim() === "")) {
    index += 1;
  }
  return `${header}\n${lines.slice(index).join("\n").trimEnd()}\n`;
}

/**
 * Give every open enum's generated `StrEnum` an `enum._missing_` hook, so an
 * unrecognised member decodes to the fallback instead of raising.
 *
 * This is the whole Python cost of the tolerance policy, and it is a
 * post-processing step because `datamodel-code-generator` has no option that
 * emits it: measured, a pydantic field typed with a plain generated `StrEnum`
 * raises `ValidationError` on any value outside the members, and prose in a
 * schema `description` does not change a generated validator. Pydantic v2 routes
 * enum validation through `EnumType.__call__`, so `_missing_` is the one hook
 * that is consulted — measured on pydantic 2.13.
 *
 * Every assertion below is deliberate: a generator upgrade that renames the base
 * class, respaces its output or drops the fallback member must fail this script
 * rather than quietly emit a strict enum, because a strict enum would make the
 * "minor bump" classification in ADR 0024's P1-S3 note false without changing a
 * word of it.
 */
function withOpenEnumFallbacks(models, open) {
  const chunks = models.split(PY_DEFINITION_SEPARATOR);
  for (const { title, fallback } of open) {
    const header = `class ${title}(StrEnum):`;
    const index = chunks.findIndex((chunk) => chunk.startsWith(`${header}\n`));
    if (index === -1) {
      throw new Error(
        `codegen: the generated models have no \`${header}\` definition to make tolerant. ` +
          "datamodel-code-generator's output shape and this script have diverged.",
      );
    }
    const chunk = chunks[index];
    const memberLine = `    ${fallback} = '${fallback}'`;
    if (!chunk.split("\n").includes(memberLine)) {
      throw new Error(
        `codegen: \`${title}\` has no \`${fallback}\` member to fall back to in the generated ` +
          "models, so the tolerant decoder would name something that does not exist.",
      );
    }
    // Written as a line list rather than one template literal: the docstring is
    // reStructuredText and carries double backticks, which have to be escaped one
    // at a time inside a template and are unreadable that way. Indentation is
    // four spaces throughout — this is a class body.
    const fallbackHook = [
      "",
      "    @classmethod",
      `    def _missing_(cls, value: object) -> ${title} | None:`,
      `        """Decode an unrecognised member as \`\`${fallback}\`\`.`,
      "",
      "        The enum is open: adding a member is a minor contract change, so a",
      "        consumer must not raise on a value a newer daemon sent. Nothing is",
      "        lost by falling back, because the accompanying ``error`` string",
      "        carries the human-readable half of the same failure and is never",
      "        rewritten. A non-string input still fails, because that is a",
      "        malformed record rather than a newer contract.",
      "",
      "        Args:",
      "            value: The value that matched no member.",
      "",
      "        Returns:",
      `            The \`\`${fallback}\`\` member for an unknown string, else None,`,
      "            which is how ``enum`` signals that the lookup really failed.",
      '        """',
      "        if isinstance(value, str):",
      `            return cls.${fallback}`,
      "        return None",
    ].join("\n");
    chunks[index] = `${chunk}\n${fallbackHook}`;
  }
  return chunks.join(PY_DEFINITION_SEPARATOR);
}

/** Run `datamodel-codegen` over the bundle and return the module it produced. */
function generateModels(open) {
  const staging = mkdtempSync(path.join(tmpdir(), "xplainer-protocol-codegen-"));
  try {
    const bundlePath = path.join(staging, "bundle.json");
    const outputPath = path.join(staging, "models.py");
    writeFileSync(bundlePath, `${JSON.stringify(buildPythonBundle(), null, 2)}\n`);

    // `--no-sync` on every `uv run`, root-scoped included: the workspace shares
    // one environment and a bare `uv run` would prune the other members out of
    // it (plan S0.7 rule 3).
    const result = spawnSync(
      "uv",
      [
        "run",
        "--no-sync",
        "datamodel-codegen",
        "--input",
        bundlePath,
        "--input-file-type",
        "jsonschema",
        "--output",
        outputPath,
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.13",
        "--use-standard-collections",
        "--use-union-operator",
        "--use-schema-description",
        "--field-constraints",
        "--collapse-root-models",
        "--disable-timestamp",
        "--custom-file-header",
        `# ${MARKER}`,
      ],
      { cwd: REPO_ROOT, encoding: "utf8" },
    );
    if (result.status !== 0) {
      process.stderr.write(result.stdout ?? "");
      process.stderr.write(result.stderr ?? "");
      throw new Error(`codegen: datamodel-codegen exited ${result.status}`);
    }
    return withOpenEnumFallbacks(replaceHeader(readFileSync(outputPath, "utf8"), PY_HEADER), open);
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}

/** The frozen tool-name and engine-owned-file tuples, Python side. */
function generatePyManifest(names, engineOwned) {
  const entries = names.map((name) => `    ${JSON.stringify(name)},`).join("\n");
  const engineEntries = engineOwned.map((name) => `    ${JSON.stringify(name)},`).join("\n");
  return `${PY_HEADER}
"""The eight explainer tools and the five scaffold files the engine owns.

The tuples are the whole point: every surface that serves the protocol iterates
them rather than repeating the names, so a tool cannot be added to one surface
and forgotten on another, and the engine-owned list cannot be enforced on one
backend and not the next. Change schemas/manifest.json and regenerate.
"""

TOOL_NAMES: tuple[str, ...] = (
${entries}
)

# The scaffold files an agent may not write. They mount the narration audio, the
# caption track and the per-segment sequencing, so a rewritten one can ship a
# silent video. explainer_put_source refuses them; the agent owns Scenes.tsx and
# the files it imports instead.
ENGINE_OWNED_FILES: tuple[str, ...] = (
${engineEntries}
)

__all__ = ["ENGINE_OWNED_FILES", "TOOL_NAMES"]
`;
}

/** The generated Python package's `__init__`, so the directory is importable. */
function generatePyInit() {
  return `${PY_HEADER}
"""Generated bindings for the xplainer tool contract.

Nothing in this package is written by hand. Import the stable re-exports from
xplainer_protocol itself instead of reaching in here.
"""
`;
}

// ── Entry point ────────────────────────────────────────────────────────────

async function main() {
  const check = process.argv.includes("--check");
  const names = toolNames();
  const engineOwned = engineOwnedFiles();
  const version = contractVersion();
  const open = openEnums();

  const outputs = new Map([
    [path.join(TS_OUT_DIR, "types.ts"), await generateTypes()],
    [path.join(TS_OUT_DIR, "manifest.ts"), generateTsManifest(names, engineOwned, version)],
    [path.join(TS_OUT_DIR, "open-enums.ts"), generateTsOpenEnums(open)],
    [path.join(PY_OUT_DIR, "models.py"), generateModels(open)],
    [path.join(PY_OUT_DIR, "manifest.py"), generatePyManifest(names, engineOwned)],
    [path.join(PY_OUT_DIR, "__init__.py"), generatePyInit()],
  ]);

  if (check) {
    const stale = [];
    for (const [file, content] of outputs) {
      let onDisk = null;
      try {
        onDisk = readFileSync(file, "utf8");
      } catch {
        onDisk = null;
      }
      if (onDisk !== content) {
        stale.push(path.relative(REPO_ROOT, file));
      }
    }
    if (stale.length > 0) {
      process.stderr.write(
        `codegen: generated output is stale:\n${stale.map((f) => `  ${f}`).join("\n")}\n` +
          "Run `pnpm --filter @xplainer/protocol codegen` and commit the result.\n",
      );
      process.exitCode = 1;
      return;
    }
    process.stdout.write(`codegen: ${outputs.size} generated files are up to date\n`);
    return;
  }

  await mkdir(TS_OUT_DIR, { recursive: true });
  await mkdir(PY_OUT_DIR, { recursive: true });
  for (const [file, content] of outputs) {
    writeFileSync(file, content);
    process.stdout.write(`codegen: wrote ${path.relative(REPO_ROOT, file)}\n`);
  }
}

await main();
